// Autogenerated PL460 to C++ Code
// File: P3Test1.cpp

#include <iostream>
#include "Object.h"
using namespace std;

int main() {
	cout << 5;
	cout << endl;
	cout << -101;
	cout << endl;
	cout << 0;
	cout << endl;
	cout << 3.14159;
	cout << endl;
	cout << -3.5;
	cout << endl;
}

